### ISSUE TITLE
k2 packages not installing on mac M2 Os ventura 13.1 

### ISSUE THREAD

**Issue by duduwithmagic** [lifeiteng/vall-e#126]
#tried both cuda version as in documentation 
pip install https://huggingface.co/csukuangfj/k2/resolve/main/cuda/k2-1.23.4.dev20230224+cuda11.6.torch1.13.1-cp310-cp310-linux_x86_64.whl

ERROR: k2-1.23.4.dev20230224+cuda11.6.torch1.13.1-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

#and cpu version 
pip install https://huggingface.co/csukuangfj/k2/resolve/main/cpu/k2-1.24.3.dev20230524+cpu.torch2.0.1-cp39-cp39-linux_x86_64.whl

ERROR: k2-1.24.3.dev20230524+cpu.torch2.0.1-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.

PS.  followed instructions except used torch Version: 2.0.1.  is it necessary to down grade to 1.13.1 ?

**Comment by chenjiasheng** [comment]
I think you should try the project inside a linux docker container if you are on IOS. Otherwise you would get more troubles not only k2.



---Original---
From: ***@***.***&gt;
Date: Sat, May 27, 2023 02:11 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [lifeiteng/vall-e] k2 packages not installing on mac M2 Os ventura13.1  (Issue #126)




 
#tried both cuda version as in documentation
 pip install https://huggingface.co/csukuangfj/k2/resolve/main/cuda/k2-1.23.4.dev20230224+cuda11.6.torch1.13.1-cp310-cp310-linux_x86_64.whl
 
ERROR: k2-1.23.4.dev20230224+cuda11.6.torch1.13.1-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
 
#and cpu version
 pip install https://huggingface.co/csukuangfj/k2/resolve/main/cpu/k2-1.24.3.dev20230524+cpu.torch2.0.1-cp39-cp39-linux_x86_64.whl
 
ERROR: k2-1.24.3.dev20230524+cpu.torch2.0.1-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
